#pragma once
enum class eMessageType
{
	LoadNext,
	LoadPrevious,
	LoadHiddenRoom,
	LoadMainRoom,
	PlayerDeath,
	PlayerSafeLanded,
	PlayerReachedBonfire,

	KilledFocus,
	SetFocus,
	TurnedInCollectible,
	Vibrate,

	PlayerLandedParticle,
	PlayerBashedPlayerParticle,
	PlayerBashedSmallParticle,
	PlayerLedgeRightGrabbedHandParticle,
	PlayerLedgeRightGrabbedLegParticle,
	PlayerLedgeLeftGrabbedHandParticle,
	PlayerLedgeLeftGrabbedLegParticle,
	EnemyShootingBulletHitParticle,
	EnemyBulletTrailEmitter,
	EnemyShootingTrailParticle,
	RainEffectForegroundParticle,
	RainEffectBackgroundParticle,
	RainEffectNextScreenParticle,
	VelocityLinesParticle,
	CollectibleCollectedParticleEasy,
	CollectibleCollectedParticleMedium,
	CollectibleCollectedParticleHard,
	CollectibleTrailEffectEasy,
	CollectibleTrailEffectMedium,
	CollectibleTrailEffectHard,
	CollectibleTrailEffect,
	BonfireWakeupTopParticleEasy,
	BonfireWakeupExplosionParticleEasy,
	BonfireIdleParticleEasy,
	BonfireWakeupTopParticleMedium,
	BonfireWakeupExplosionParticleMedium,
	BonfireIdleParticleMedium,
	BonfireWakeupTopParticleHard,
	BonfireWakeupExplosionParticleHard,
	BonfireIdleParticleHard,
	DustParticleOne,
	DustParticleTwo,
	DustParticleThree,
	DustParticleStartupOne,
	DustParticleStartupTwo,
	UnstablePlatformParticle

};