#pragma once
enum class eMessageType
{
	LoadNext,
	LoadPrevious,
	LoadHiddenRoom,
	LoadMainRoom,
	PlayerDeath,
	PlayerSafeLanded,
	PlayerReachedBonfire,

	PlayerLandedParticle,
	PlayerBashedPlayerParticle,
	PlayerBashedSmallParticle,
	PlayerLedgeRightGrabbedHandParticle,
	PlayerLedgeRightGrabbedLegParticle,
	PlayerLedgeLeftGrabbedHandParticle,
	PlayerLedgeLeftGrabbedLegParticle,
	EnemyShootingBulletHitParticle,
	EnemyBulletTrailEmitter,
	EnemyShootingTrailParticle,
	RainEffectForegroundParticle,
	RainEffectBackgroundParticle,
	RainEffectNextScreenParticle,
	VelocityLinesParticle,
	CollectibleCollectedParticleEasy,
	CollectibleCollectedParticleMedium,
	CollectibleCollectedParticleHard,
	CollectibleTrailEffectEasy,
	CollectibleTrailEffectMedium,
	CollectibleTrailEffectHard,
	CollectibleTrailEffect,
	BonfireWakeupTopParticle,
	BonfireWakeupExplosionParticle,
	BonfireIdleParticle,
	UnstablePlatformParticle,

	KilledFocus,
	SetFocus,
	TurnedInCollectible,
	Vibrate
};