#pragma once


enum class eParticleEffects
{
	RainEffectNextScreenParticle,
	CollectibleTrailEffect,
	DeathEffect,
	RainEffectBackgroundParticle,
	RainEffectForegroundParticle,
	BulletEffectTrail,
	BulletEffectHit,
	FogEffect,
	PlayerFallLandEffect,
	BulletEffectTrail2,
	PlayerBashedPlayerParticle,
	PlayerBashedSmallParticle,
	PlayerLedgeRightGrabbedHandParticle,
	PlayerLedgeRightGrabbedLegParticle,
	PlayerLedgeLeftGrabbedHandParticle,
	PlayerLedgeLeftGrabbedLegParticle,
	VelocityLinesParticles,
	UnstablePlatformParticle,
	CollectibleCollectedParticleEasy,
	CollectibleCollectedParticleMedium,
	CollectibleCollectedParticleHard,
	CollectibleTrailEffectEasy,
	CollectibleTrailEffectMedium,
	CollectibleTrailEffectHard,
	BonfireWakeupTopParticleEasy,
	BonfireWakeupExplosionParticleEasy,
	BonfireIdleParticleEasy,
	BonfireWakeupTopParticleMedium,
	BonfireWakeupExplosionParticleMedium,
	BonfireIdleParticleMedium,
	BonfireWakeupTopParticleHard,
	BonfireWakeupExplosionParticleHard,
	BonfireIdleParticleHard,
	DustParticleOne,
	DustParticleTwo,
	DustParticleThree,
	DustParticleStartupOne,
	DustParticleStartupTwo
};